name: Cache Demo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Cache step
      - name: Cache Python packages
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-ec5656f

      - name: prime-cache-ec5656f
        run: echo "Cache result = ${{ steps.cache.outputs.cache-hit }}"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
